run-name: ${{ github.actor }} is deploying out ${{ github.repository }}  🚀
on: 
  push:
    branches:
      - main
jobs:    
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - name: Executing remote ssh commands using password
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command: | 
          cd /var/www/regulatoryreporting.schema.id
          git reset --hard
          git pull
          
    - name: Send message to Discord  
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Deployment ePrescription to Production"
        description: "Build and deploy ${{ github.repository }}"
        color: 0x0000ff
